name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    
    - name: List files
      run: dir /s
    
    - name: Restore packages
      run: nuget restore ElectronicJournal/ElectronicJournal/ElectronicJournal.csproj
    
    - name: Build
      run: msbuild ElectronicJournal/ElectronicJournal/ElectronicJournal.csproj /p:Configuration=Release
    
    - name: Test
      run: vstest.console.exe ElectronicJournal/ElectronicJournal.Tests/bin/Release/ElectronicJournal.Tests.dll
